"""Role-scoped endpoints.

Three audiences, three very different needs:

  MEMBER    a resident with a doorbell camera. Sees their own property, their own
            devices, their own claims. Nothing else — a member must never be able to
            enumerate other households.

  FRAUD     Discovery's claims investigators. Sees every claim, opens one, and gets
            an analytical report placing it against five years of history, plus the
            movement trails that camera evidence reconstructs.

  SECURITY  a partner response company. Sees hotspot briefings and route economics
            for the areas it covers. Never sees claim amounts, member identities, or
            raw evidence — it gets where to go and when, not who.

The claim report is *computed*, not generated by a language model. Every number in
it can be traced back to a row in the workbook, which matters when an investigator
has to defend a decision. Where a narrative layer would help, the endpoint returns
structured findings the caller can render or summarise.
"""
from __future__ import annotations

import math
import statistics
from collections import Counter, defaultdict
from datetime import datetime, timedelta
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

from sentinel_ops.claims_bridge import load_claims_hotspots, list_metros

router = APIRouter(tags=["roles"])

OPERATIONS_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = OPERATIONS_ROOT.parents[1]

# The supplied Discovery workbook. First match wins.
WORKBOOK_CANDIDATES = [
    REPO_ROOT / "services" / "claims" / "data" / "raw",
    REPO_ROOT / "services" / "claims" / "data",
    REPO_ROOT / "data",
    REPO_ROOT,
]

# Suburb -> approximate centroid. Only the pilot suburbs need to be exact; the rest
# fall back to their metro centre so the map stays honest about what it knows.
METRO_CENTRES = {
    "Gauteng": (-26.1, 28.05),
    "Cape Town": (-33.95, 18.48),
    "Other": (-29.0, 25.0),
}


# --------------------------------------------------------------------- workbook
@lru_cache(maxsize=1)
def _load_workbook() -> tuple[list[dict[str, Any]], str]:
    """Read the claims workbook once and cache it."""
    try:
        import pandas as pd
    except ImportError:
        return [], "pandas not installed"

    for base in WORKBOOK_CANDIDATES:
        if not base.exists():
            continue
        for path in sorted(base.glob("*.xlsx")):
            try:
                df = pd.read_excel(path)
            except Exception:
                continue
            if "CLAIM_AMOUNT" not in df.columns:
                continue
            def clean(v):
                """pandas leaves NaN in float columns even after .where(notna) — strip it here."""
                if v is None:
                    return None
                if isinstance(v, float) and math.isnan(v):
                    return None
                return v

            rows = []
            for i, r in enumerate(df.to_dict("records"), 1):
                r = {k: clean(v) for k, v in r.items()}
                dt = r.get("INCIDENT_DATE_TIME")
                suburb = r.get("SUBURB")
                year = r.get("VEHICLE_YEAR")
                rows.append({
                    "incident_id": r.get("Incident") or f"INC-{i:05d}",
                    "peril": r.get("PERIL"),
                    "suburb": str(suburb).strip().title() if suburb else None,
                    "item_type": r.get("ITEM_TYPE"),
                    "item_category": r.get("ITEM_CATEGORY"),
                    "peril_descr": r.get("ITEM_PERIL_DESCR"),
                    "vehicle_make": r.get("VEHICLE_MAKE"),
                    "vehicle_model": r.get("VEHICLE_MODEL"),
                    "vehicle_year": int(year) if year else None,
                    "incident_at": dt.isoformat() if hasattr(dt, "isoformat") else None,
                    "amount": float(r.get("CLAIM_AMOUNT") or 0),
                })
            return rows, str(path)
    return [], "workbook not found"


def claims() -> list[dict[str, Any]]:
    return _load_workbook()[0]


@lru_cache(maxsize=1)
def _suburb_stats() -> dict[str, dict[str, Any]]:
    """Per-suburb distribution, so a single claim can be placed in context."""
    by: dict[str, list[dict]] = defaultdict(list)
    for c in claims():
        if c["suburb"]:
            by[c["suburb"]].append(c)
    out = {}
    for suburb, rows in by.items():
        amounts = sorted(r["amount"] for r in rows)
        hours = [datetime.fromisoformat(r["incident_at"]).hour for r in rows if r["incident_at"]]
        days = [datetime.fromisoformat(r["incident_at"]).strftime("%A") for r in rows if r["incident_at"]]
        out[suburb] = {
            "count": len(rows),
            "total": sum(amounts),
            "median": statistics.median(amounts) if amounts else 0,
            "p90": amounts[int(len(amounts) * 0.9)] if amounts else 0,
            "amounts": amounts,
            "peak_hours": [h for h, _ in Counter(hours).most_common(3)],
            "peak_days": [d for d, _ in Counter(days).most_common(2)],
            "perils": dict(Counter(r["peril"] for r in rows).most_common(4)),
        }
    return out


def _percentile(sorted_vals: list[float], v: float) -> float:
    if not sorted_vals:
        return 0.0
    lo, hi = 0, len(sorted_vals)
    while lo < hi:
        mid = (lo + hi) // 2
        if sorted_vals[mid] < v:
            lo = mid + 1
        else:
            hi = mid
    return round(100 * lo / len(sorted_vals), 1)


# --------------------------------------------------------------------- MEMBER
class CameraRegistration(BaseModel):
    household: str = Field(..., min_length=3, description="street address of the property")
    suburb: str
    metro: str = "Gauteng"
    latitude: float
    longitude: float
    device_label: str = "Doorbell camera"
    consent_acknowledged: bool = Field(
        ..., description="the member confirms every adult at the property has agreed"
    )


_member_cameras: list[dict[str, Any]] = []


@router.post("/api/member/cameras")
def register_camera(body: CameraRegistration):
    """A member adds their own doorbell camera to the mesh.

    Consent is a hard gate, not a checkbox we log and ignore. A camera pointed at a
    shared street records people who never agreed to anything, so the member has to
    affirm the household consented before the device is accepted.
    """
    if not body.consent_acknowledged:
        raise HTTPException(
            status_code=422,
            detail="consent_acknowledged must be true — a camera cannot join the mesh "
                   "without the household confirming agreement",
        )
    if not (-35 < body.latitude < -22 and 16 < body.longitude < 33):
        raise HTTPException(status_code=422, detail="coordinates fall outside South Africa")

    seq = len(_member_cameras) + 1
    prefix = "".join(w[0] for w in body.suburb.split()[:3]).upper()[:3] or "MEM"
    cam = {
        "camera_id": f"CAM-{prefix}-{seq:02d}",
        "household": body.household,
        "suburb": body.suburb.strip().title(),
        "metro": body.metro,
        "latitude": body.latitude,
        "longitude": body.longitude,
        "device_label": body.device_label,
        "status": "PENDING_ACTIVATION",
        "mode": "NORMAL",
        "owner": "member",
        "registered_at": datetime.now().astimezone().isoformat(),
    }
    # Inherit the mode implied by the geofence it lands in.
    try:
        hotspots, _ = load_claims_hotspots(body.metro)
        for h in hotspots:
            if h.name.strip().lower() == cam["suburb"].lower():
                risk = getattr(h, "operational_priority", 0) or 0
                cam["hotspot_id"] = h.hotspot_id
                cam["geofence_risk"] = round(float(risk), 1)
                cam["mode"] = "HEIGHTENED" if float(risk) >= 60 else "NORMAL"
                break
    except Exception:
        pass
    _member_cameras.append(cam)
    return {
        "camera": cam,
        "next_steps": [
            "Pair the device using the activation code sent to the member.",
            "Point the camera at your own entrance, not a neighbour's property.",
            "Routine video stays on the device — only event crops are uploaded.",
        ],
    }


@router.get("/api/member/cameras")
def member_cameras():
    return {"count": len(_member_cameras), "cameras": _member_cameras}


@router.get("/api/member/summary")
def member_summary(suburb: str = Query(..., description="the member's suburb")):
    """What a resident is allowed to see: their own area, never other households."""
    stats = _suburb_stats().get(suburb.strip().title())
    mine = [c for c in _member_cameras if c["suburb"].lower() == suburb.strip().lower()]
    if not stats:
        return {
            "suburb": suburb,
            "known": False,
            "message": "No claims history for this suburb in the supplied data.",
            "cameras": mine,
        }
    return {
        "suburb": suburb.strip().title(),
        "known": True,
        "incidents_5y": stats["count"],
        "peak_hours": stats["peak_hours"],
        "peak_days": stats["peak_days"],
        "common_perils": stats["perils"],
        "cameras": mine,
        "privacy_note": "Members see area-level patterns only. Individual claims, "
                        "amounts and other households are not exposed to this role.",
    }


# --------------------------------------------------------------------- FRAUD
@router.get("/api/fraud/claims")
def browse_claims(
    q: str | None = None,
    peril: str | None = None,
    suburb: str | None = None,
    item_type: str | None = None,
    min_amount: float | None = None,
    sort: Literal["recent", "amount", "suburb"] = "recent",
    limit: int = Query(50, ge=1, le=500),
    offset: int = 0,
):
    """Every claim, filterable. Fraud role only."""
    rows = claims()
    if not rows:
        raise HTTPException(status_code=503, detail=_load_workbook()[1])

    def keep(c):
        if peril and (c["peril"] or "").lower() != peril.lower():
            return False
        if suburb and (c["suburb"] or "").lower() != suburb.lower():
            return False
        if item_type and (c["item_type"] or "").lower() != item_type.lower():
            return False
        if min_amount and c["amount"] < min_amount:
            return False
        if q:
            hay = " ".join(str(c.get(k) or "") for k in
                           ("incident_id", "suburb", "peril", "vehicle_make", "vehicle_model"))
            if q.lower() not in hay.lower():
                return False
        return True

    filtered = [c for c in rows if keep(c)]
    if sort == "amount":
        filtered.sort(key=lambda c: c["amount"], reverse=True)
    elif sort == "suburb":
        filtered.sort(key=lambda c: (c["suburb"] or "", -c["amount"]))
    else:
        filtered.sort(key=lambda c: c["incident_at"] or "", reverse=True)

    return {
        "total": len(filtered),
        "offset": offset,
        "limit": limit,
        "value": round(sum(c["amount"] for c in filtered), 2),
        "claims": filtered[offset: offset + limit],
        "facets": {
            "perils": dict(Counter(c["peril"] for c in filtered).most_common(8)),
            "item_types": dict(Counter(c["item_type"] for c in filtered).most_common()),
        },
    }


@router.get("/api/fraud/claims/{incident_id}/report")
def claim_report(incident_id: str):
    """An analytical report on one claim.

    Every figure here is computed from the workbook and can be traced back to rows an
    investigator can pull. Findings are graded INFO / WATCH / FLAG. A FLAG is a reason
    to look closer — it is explicitly not an accusation, and the response says so.
    """
    rows = claims()
    claim = next((c for c in rows if c["incident_id"] == incident_id), None)
    if not claim:
        raise HTTPException(status_code=404, detail=f"unknown claim {incident_id}")

    stats = _suburb_stats().get(claim["suburb"] or "", None)
    findings: list[dict[str, str]] = []
    when = datetime.fromisoformat(claim["incident_at"]) if claim["incident_at"] else None

    # --- sample size first: a percentile from three rows means nothing ---
    if stats and stats["count"] < 10:
        findings.append({
            "level": "WATCH", "code": "SMALL_SAMPLE",
            "title": f"Only {stats['count']} claim(s) on record for {claim['suburb']}",
            "detail": "The comparisons below rest on a very small sample, so percentiles and "
                      "medians for this suburb are not meaningful. Compare against the peril "
                      "or item type nationally instead.",
        })

    # --- amount vs the suburb's own distribution ---
    pct = None
    if stats and stats["amounts"]:
        pct = _percentile(stats["amounts"], claim["amount"])
        ratio = claim["amount"] / stats["median"] if stats["median"] else 0
        if pct >= 99:
            findings.append({
                "level": "FLAG", "code": "AMOUNT_EXTREME",
                "title": f"Amount sits in the top 1% for {claim['suburb']}",
                "detail": f"R{claim['amount']:,.0f} against a suburb median of "
                          f"R{stats['median']:,.0f} ({ratio:.1f}x). High-value claims are "
                          f"legitimate every day — this only means the file deserves a second reader.",
            })
        elif pct >= 90:
            findings.append({
                "level": "WATCH", "code": "AMOUNT_HIGH",
                "title": f"Amount is in the {pct:.0f}th percentile for {claim['suburb']}",
                "detail": f"R{claim['amount']:,.0f} vs median R{stats['median']:,.0f}.",
            })
        else:
            findings.append({
                "level": "INFO", "code": "AMOUNT_TYPICAL",
                "title": f"Amount is typical for {claim['suburb']} ({pct:.0f}th percentile)",
                "detail": f"R{claim['amount']:,.0f} vs median R{stats['median']:,.0f}.",
            })

    # --- national context, which is always well-populated ---
    peer = [c["amount"] for c in rows
            if c["item_type"] == claim["item_type"] and c["peril"] == claim["peril"]]
    if peer:
        peer.sort()
        npct = _percentile(peer, claim["amount"])
        findings.append({
            "level": "FLAG" if npct >= 99.5 else "WATCH" if npct >= 97 else "INFO",
            "code": "AMOUNT_NATIONAL",
            "title": f"{npct:.1f}th percentile against all {len(peer):,} "
                     f"{claim['peril']} / {claim['item_type']} claims",
            "detail": f"R{claim['amount']:,.0f} against a national median of "
                      f"R{statistics.median(peer):,.0f} for this peril and item type. "
                      f"This comparison uses the whole book, so it holds even where the "
                      f"suburb sample is thin.",
        })

    # --- timestamp quality ---
    if when and when.hour == 0 and when.minute == 0:
        midnight = sum(1 for c in rows
                       if c["incident_at"] and c["incident_at"].endswith("T00:00:00"))
        findings.append({
            "level": "WATCH", "code": "TIME_MIDNIGHT",
            "title": "Incident time recorded as exactly midnight",
            "detail": f"{midnight:,} claims in the book share this timestamp, so it usually means "
                      f"the time was unknown at capture rather than anything suspicious. "
                      f"Camera retrieval for this claim cannot rely on the hour.",
        })
    elif when and stats:
        if when.hour in stats["peak_hours"]:
            findings.append({
                "level": "INFO", "code": "TIME_PEAK",
                "title": f"Occurred inside {claim['suburb']}'s peak risk window",
                "detail": f"{when.strftime('%H:%M on %A')} — this suburb's busiest hours are "
                          f"{', '.join(f'{h:02d}:00' for h in stats['peak_hours'])}.",
            })
        else:
            findings.append({
                "level": "INFO", "code": "TIME_OFFPEAK",
                "title": "Occurred outside the suburb's usual pattern",
                "detail": f"{when.strftime('%H:%M on %A')}; peak hours here are "
                          f"{', '.join(f'{h:02d}:00' for h in stats['peak_hours'])}.",
            })

    # --- nearby claims in a tight window (cluster or spree) ---
    cluster = []
    if when and claim["suburb"]:
        for c in rows:
            if c["incident_id"] == incident_id or c["suburb"] != claim["suburb"] or not c["incident_at"]:
                continue
            if abs((datetime.fromisoformat(c["incident_at"]) - when).total_seconds()) <= 72 * 3600:
                cluster.append(c)
    if len(cluster) >= 3:
        findings.append({
            "level": "FLAG", "code": "CLUSTER",
            "title": f"{len(cluster)} other claims in {claim['suburb']} within 72 hours",
            "detail": "A tight cluster usually means a spree rather than anything about this "
                      "claimant. It is the strongest argument for pulling camera evidence "
                      "across the whole window, not just this address.",
        })
    elif cluster:
        findings.append({
            "level": "INFO", "code": "CLUSTER_LIGHT",
            "title": f"{len(cluster)} other claim(s) nearby within 72 hours",
            "detail": "Worth cross-referencing when retrieving evidence.",
        })

    # --- vehicle context ---
    if claim["vehicle_make"]:
        make_rows = [c for c in rows if c["vehicle_make"] == claim["vehicle_make"]]
        rank = sorted(Counter(c["vehicle_make"] for c in rows if c["vehicle_make"]).items(),
                      key=lambda kv: -kv[1])
        pos = next((i + 1 for i, (m, _) in enumerate(rank) if m == claim["vehicle_make"]), None)
        findings.append({
            "level": "INFO", "code": "VEHICLE_CONTEXT",
            "title": f"{claim['vehicle_make']} is #{pos} most-claimed make in the book",
            "detail": f"{len(make_rows):,} claims involve this make. "
                      f"Model on file: {claim['vehicle_model'] or 'not recorded'}.",
        })

    # --- camera coverage at the time of the incident ---
    coverage = _coverage_for(claim["suburb"])
    if coverage["cameras"]:
        findings.append({
            "level": "INFO", "code": "COVERAGE",
            "title": f"{len(coverage['cameras'])} participating camera(s) in {claim['suburb']}",
            "detail": "Incident Time Machine can reconstruct the window around this claim.",
        })
    else:
        findings.append({
            "level": "WATCH", "code": "NO_COVERAGE",
            "title": f"No participating cameras in {claim['suburb']}",
            "detail": "No camera evidence can be retrieved for this claim. This is exactly the "
                      "gap the Coverage Optimizer is meant to close.",
        })

    flags = sum(1 for f in findings if f["level"] == "FLAG")
    watches = sum(1 for f in findings if f["level"] == "WATCH")
    if flags >= 2:
        rec, priority = "Refer for investigator review before settlement.", "HIGH"
    elif flags == 1:
        rec, priority = "Pull camera evidence for the incident window, then reassess.", "MEDIUM"
    elif watches:
        rec, priority = "Proceed, noting the data-quality caveats above.", "LOW"
    else:
        rec, priority = "Nothing anomalous found. Proceed on normal terms.", "ROUTINE"

    return {
        "claim": claim,
        "context": {
            "suburb_incidents_5y": stats["count"] if stats else 0,
            "suburb_total_value": round(stats["total"], 2) if stats else 0,
            "suburb_median": round(stats["median"], 2) if stats else 0,
            "amount_percentile": pct,
            "peak_hours": stats["peak_hours"] if stats else [],
            "peak_days": stats["peak_days"] if stats else [],
        },
        "coverage": coverage,
        "cluster": sorted(cluster, key=lambda c: c["incident_at"] or "")[:12],
        "findings": findings,
        "assessment": {
            "priority": priority,
            "recommendation": rec,
            "flags": flags,
            "watches": watches,
        },
        "disclaimer": "Findings are statistical context computed from the supplied claims "
                      "workbook. They indicate where a human should look, not whether a claim "
                      "is fraudulent. No claim is declined on the basis of this report.",
    }


def _coverage_for(suburb: str | None) -> dict[str, Any]:
    if not suburb:
        return {"suburb": None, "cameras": []}
    try:
        from sentinel_ops.camera_upload import CAMERA_ROSTER
        roster = list(CAMERA_ROSTER)
    except Exception:
        roster = []
    roster += _member_cameras
    cams = [c for c in roster if (c.get("suburb") or "").lower() == suburb.lower()]
    return {"suburb": suburb, "cameras": [
        {"camera_id": c["camera_id"], "household": c.get("household"),
         "latitude": c.get("latitude"), "longitude": c.get("longitude")} for c in cams]}


# --------------------------------------------------------------- MOVEMENT TRAILS
@router.get("/api/fraud/movement")
def movement_trails(days: int = Query(30, ge=1, le=365), min_sightings: int = 2):
    """Reconstructed movement across cameras — the 'activity trail' view.

    Each confirmed or candidate pattern becomes a trail: its sightings ordered in
    time, joined into a path between camera positions. Segments travelled by more
    than one pattern accumulate weight, which is what makes the aggregate heat layer.

    This shows where *evidence* recurs, not where people go. Only patterns the system
    already surfaced appear here, and none of them carries an identity.
    """
    try:
        from sentinel_ops.patterns_api import registry
        reg = registry()
        patterns = reg.store.list_patterns()
    except Exception as exc:
        raise HTTPException(status_code=503, detail=f"pattern registry unavailable: {exc}")

    try:
        from sentinel_ops.camera_upload import CAMERA_ROSTER
        positions = {c["camera_id"]: (c["latitude"], c["longitude"], c.get("suburb"))
                     for c in list(CAMERA_ROSTER) + _member_cameras}
    except Exception:
        positions = {}

    cutoff = datetime.now().astimezone() - timedelta(days=days)
    trails, segments = [], Counter()

    for p in patterns:
        if p.occurrence_count < min_sightings:
            continue
        pts = []
        for cam_id in p.camera_ids:
            if cam_id in positions:
                lat, lon, sub = positions[cam_id]
                pts.append({"camera_id": cam_id, "suburb": sub, "latitude": lat, "longitude": lon})
        if len(pts) < 2:
            continue
        dist = 0.0
        for a, b in zip(pts, pts[1:]):
            dist += _haversine(a["latitude"], a["longitude"], b["latitude"], b["longitude"])
            key = tuple(sorted([a["camera_id"], b["camera_id"]]))
            segments[key] += 1
        trails.append({
            "pattern_id": p.pattern_id,
            "kind": p.kind,
            "status": p.status,
            "description": p.describe(),
            "sightings": p.occurrence_count,
            "distance_km": round(dist, 2),
            "first_seen": p.first_seen,
            "last_seen": p.last_seen,
            "points": pts,
        })

    corridors = []
    for (a, b), weight in segments.most_common():
        if a in positions and b in positions:
            corridors.append({
                "from": a, "to": b, "weight": weight,
                "from_point": {"latitude": positions[a][0], "longitude": positions[a][1]},
                "to_point": {"latitude": positions[b][0], "longitude": positions[b][1]},
            })

    hot = Counter()
    for t in trails:
        for pt in t["points"]:
            hot[(pt["camera_id"], pt["latitude"], pt["longitude"], pt["suburb"])] += 1

    return {
        "window_days": days,
        "trail_count": len(trails),
        "trails": sorted(trails, key=lambda t: -t["sightings"]),
        "corridors": corridors,
        "nodes": [{"camera_id": c, "latitude": la, "longitude": lo, "suburb": s, "weight": w}
                  for (c, la, lo, s), w in hot.most_common()],
        "note": "Trails are reconstructed from evidence patterns, not from tracking "
                "individuals. Nothing here is attributed to a named person.",
    }


def _haversine(lat1, lon1, lat2, lon2) -> float:
    R = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp, dl = math.radians(lat2 - lat1), math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


# --------------------------------------------------------------------- SECURITY
@router.get("/api/security/briefing")
def security_briefing(metro: str = "Gauteng", shift: Literal["day", "night"] = "night"):
    """Operational briefing for a partner response company.

    Deliberately excludes claim amounts, member identities and raw evidence. A
    security partner needs to know where to be and when — not what anyone lost or
    who they are.
    """
    try:
        hotspots, meta = load_claims_hotspots(metro)
    except Exception as exc:
        raise HTTPException(status_code=503, detail=str(exc))

    ranked = sorted(hotspots, key=lambda h: -(getattr(h, "operational_priority", 0) or 0))
    stats = _suburb_stats()
    items = []
    for h in ranked:
        s = stats.get(h.name, {})
        hours = s.get("peak_hours", [])
        night = [x for x in hours if x >= 18 or x <= 5]
        day = [x for x in hours if 6 <= x <= 17]
        relevant = night if shift == "night" else day
        pw = getattr(h, "peak_window", None)
        items.append({
            "hotspot_id": h.hotspot_id,
            "area": h.name,
            "priority": round(float(getattr(h, "operational_priority", 0) or 0), 1),
            "band": "HIGH" if (getattr(h, "operational_priority", 0) or 0) >= 60
                    else "MEDIUM" if (getattr(h, "operational_priority", 0) or 0) >= 40 else "LOW",
            "dominant_peril": getattr(h, "main_peril", None),
            "incidents_5y": s.get("count"),
            "peak_hours_all": hours,
            "peak_hours_this_shift": relevant,
            "peak_days": s.get("peak_days", []),
            "geofence_radius_km": getattr(h, "geofence_radius_km", None),
            "location": {"latitude": h.location.latitude, "longitude": h.location.longitude}
                        if getattr(h, "location", None) else None,
            "recommended_presence": (
                "sustained patrol through the risk window" if (getattr(h, "operational_priority", 0) or 0) >= 60
                else "scheduled passes at peak hours" if (getattr(h, "operational_priority", 0) or 0) >= 40
                else "routine coverage"),
        })

    coverage_gaps = []
    for it in items:
        cams = _coverage_for(it["area"])["cameras"]
        if it["band"] in ("HIGH", "MEDIUM") and not cams:
            coverage_gaps.append({
                "area": it["area"], "priority": it["priority"],
                "reason": "high risk with no participating camera — evidence cannot be retrieved here",
            })

    return {
        "metro": metro,
        "shift": shift,
        "generated_at": datetime.now().astimezone().isoformat(),
        "hotspots": items,
        "focus": [i["area"] for i in items[:3]],
        "coverage_gaps": coverage_gaps,
        "excluded": ["claim amounts", "member identities", "raw camera evidence"],
        "note": "Priority scores are derived from Discovery claims history fused with "
                "SAPS context. They rank where attention is worth spending; they are not "
                "predictions that a crime will occur.",
    }


class SiteProposal(BaseModel):
    area: str
    latitude: float
    longitude: float
    reason: str = "partner-nominated coverage point"


@router.post("/api/security/sites")
def propose_site(body: SiteProposal, metro: str = "Gauteng"):
    """A security partner nominates an extra location to fold into route planning."""
    try:
        hotspots, _ = load_claims_hotspots(metro)
    except Exception as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    nearest, best = None, 1e9
    for h in hotspots:
        if not getattr(h, "location", None):
            continue
        d = _haversine(body.latitude, body.longitude, h.location.latitude, h.location.longitude)
        if d < best:
            nearest, best = h, d
    site = {
        "site_id": "SITE-" + str(abs(hash((body.area, round(body.latitude, 4)))) % 100000).zfill(5),
        "area": body.area, "latitude": body.latitude, "longitude": body.longitude,
        "reason": body.reason,
        "nearest_hotspot": nearest.hotspot_id if nearest else None,
        "nearest_hotspot_name": nearest.name if nearest else None,
        "distance_km": round(best, 2) if nearest else None,
        "inherits_priority": round(float(getattr(nearest, "operational_priority", 0) or 0), 1)
                             if nearest and best <= 3 else None,
    }
    _security_sites.append(site)
    return {
        "site": site,
        "note": "Nominated sites join route planning at the priority of the hotspot they "
                "fall inside. Beyond 3 km they carry no inherited risk weight — the claims "
                "data has nothing to say about them.",
    }


_security_sites: list[dict[str, Any]] = []


@router.get("/api/security/sites")
def list_sites():
    return {"count": len(_security_sites), "sites": _security_sites}


@router.on_event("startup")
async def _warm_cache() -> None:
    """Read the workbook once at boot.

    Parsing 15k rows takes several seconds. Doing it lazily means the first
    investigator to open the claims browser waits — and in a demo that pause reads
    as a hang. Warming here moves the cost to startup where nobody is watching.
    """
    import asyncio

    def load():
        rows, src = _load_workbook()
        if rows:
            _suburb_stats()
        return len(rows), src

    try:
        count, src = await asyncio.get_event_loop().run_in_executor(None, load)
        print(f"[roles] claims workbook ready: {count:,} rows from {src}")
    except Exception as exc:  # never block startup on this
        print(f"[roles] workbook warm-up skipped: {exc}")


@router.get("/api/roles")
def roles():
    """What each role may see. Useful for the UI and for the privacy write-up."""
    return {
        "roles": [
            {"id": "member", "label": "Discovery member",
             "home": "property",
             "sees": ["own cameras", "own suburb risk pattern", "phone camera contribution", "provisional Vitality Secure status"],
             "never": ["other households", "individual claim files", "evidence patterns", "patrol intelligence"]},
            {"id": "fraud", "label": "Fraud & claims",
             "home": "claims",
             "sees": ["all claims", "traceable claim analytics", "claim-linked evidence timelines", "anonymous movement corridors"],
             "never": ["member camera control", "security partner site administration"]},
            {"id": "security", "label": "Security partner",
             "home": "briefing",
             "sees": ["hotspot briefings", "patrol routes", "coverage gaps", "partner-nominated sites"],
             "never": ["claim amounts", "member identities", "raw evidence media"]},
        ],
        "principle": "The dashboard displays the minimum needed for each role. This hackathon "
                     "build uses a demo role selector; production must enforce the same scopes "
                     "with authenticated identities and API authorisation, for example AWS Cognito and RBAC.",
    }
